In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.examples.tutorials.mnist import input_data
import os, sys, time, datetime
import matplotlib.pyplot as plt
from bnn_shson import *

%matplotlib inline


In [2]:
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [3]:
#sess = tf.InteractiveSession()
sess = tf.InteractiveSession(config=tf.ConfigProto(gpu_options=tf.GPUOptions(per_process_gpu_memory_fraction=0.2)))


In [4]:
batch_size = 50

In [5]:
#bnn = bnn_model(shape, mu = 0.1, rho = 0.1, n_samples = 10, outact = tf.sigmoid, seed = 1234, lr = 1e-8)
bnn = bnn_model([784, 100, 100, 10], size_batch = batch_size, mu = 0.1, rho = 0.1, n_samples = 10, outact = tf.sigmoid, seed = 1234, lr = 1e-8)

TypeError: int() argument must be a string or a number, not 'Tensor'

In [7]:
a = tf.constant(2, shape = [3, 4])

In [8]:
sess.run(tf.initialize_all_variables())

In [15]:
aones = tf.constant(1, shape = [3, 1])
#aa = tf.concat(1, [a, tf.ones(shape = [tf.shape(a)[0], 1])])

print tf.shape(a).eval()
#aa.eval()

[3 4]


In [ ]:
for i in range(20000):
    batch = mnist.train.next_batch(batch_size)
    feed = {bnn.x: batch[0], bnn.t: batch[1]}
    
    #if i%100 == 0:
        #train_accuracy = bnn.validate(feed)
        #print("step %d, training accuracy %g"%(i, train_accuracy))
    
    bnn.train(feed)

print("test accuracy %g"%bnn.validate({x: mnist.test.images, t: mnist.test.labels}))

In [20]:
a = tf.range(300)
aa = tf.reshape(a, [30, 10])
aaa = tf.tile(tf.expand_dims(aa, 0), [10, 1, 1])

b = tf.truncated_normal([30, 10], stddev = 0.2)

argmaxbs = tf.argmax(b, 1)

In [21]:
b.get_shape()

TensorShape([Dimension(30), Dimension(10)])

In [22]:
sess.run(tf.initialize_all_variables())

In [23]:
tf.reshape(aaa, [-1]).eval()

array([  0,   1,   2, ..., 297, 298, 299], dtype=int32)

In [26]:
ar = tf.range(30).eval()
br = ar * 10 + argmaxbs.eval()
cr = tf.tile(br, [10])

result = tf.gather(tf.reshape(aaa, [-1]), cr).eval()
print result
print result.shape
argmaxbs.eval()



[  5  11  27  32  43  57  63  76  84  97 105 118 123 138 142 158 164 172
 182 193 201 215 227 237 248 258 261 271 281 298   5  11  27  32  43  57
  63  76  84  97 105 118 123 138 142 158 164 172 182 193 201 215 227 237
 248 258 261 271 281 298   5  11  27  32  43  57  63  76  84  97 105 118
 123 138 142 158 164 172 182 193 201 215 227 237 248 258 261 271 281 298
   5  11  27  32  43  57  63  76  84  97 105 118 123 138 142 158 164 172
 182 193 201 215 227 237 248 258 261 271 281 298   5  11  27  32  43  57
  63  76  84  97 105 118 123 138 142 158 164 172 182 193 201 215 227 237
 248 258 261 271 281 298   5  11  27  32  43  57  63  76  84  97 105 118
 123 138 142 158 164 172 182 193 201 215 227 237 248 258 261 271 281 298
   5  11  27  32  43  57  63  76  84  97 105 118 123 138 142 158 164 172
 182 193 201 215 227 237 248 258 261 271 281 298   5  11  27  32  43  57
  63  76  84  97 105 118 123 138 142 158 164 172 182 193 201 215 227 237
 248 258 261 271 281 298   5  11  27  32  43  57  6

array([3, 2, 5, 3, 8, 6, 1, 0, 7, 0, 3, 7, 8, 0, 4, 5, 8, 8, 0, 2, 6, 7, 7,
       0, 3, 7, 8, 3, 8, 0])

In [16]:
tf.gather_nd(aa, [[0, 1], [3, 5]]).eval()

array([ 1, 35], dtype=int32)

In [8]:
test =  mnist.test.labels

In [9]:
test.shape

(10000, 10)

In [64]:
sess = tf.Session()

In [6]:
a = tf.Variable(tf.truncated_normal([2, 3], stddev = 0.1))
b = tf.Variable(tf.constant(-1.0, shape = [2, 3]))
c = tf.placeholder(tf.float32, [None, 10])

In [7]:
sess.run(tf.initialize_all_variables())

In [18]:
tf.argmax(c, [1]).eval(feed_dict = {c: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [15, 14, 13, 12, 11, 10, 10, 10, 10, 10]]})

ValueError: Shapes (1,) and () are incompatible

In [11]:
tf.shape(a).eval()[0]

2

In [66]:
with sess:
    sess.run(tf.initialize_all_variables())
    print a.eval()
    print tf.tile(a, [6, 3]).eval()
    print tf.tile(tf.expand_dims(a, 0), [2, 1, 1]).eval()
    a = a * b
    print a.eval()
    print tf.tile(a, [6, 3]).eval()
    print tf.transpose(a, [0, 1]).eval()
    print tf.transpose(a, [1, 0]).eval()

[[-0.04836457  0.11699509 -0.10365508]
 [-0.11315618 -0.14960578 -0.13785519]]
[[-0.04836457  0.11699509 -0.10365508 -0.04836457  0.11699509 -0.10365508
  -0.04836457  0.11699509 -0.10365508]
 [-0.11315618 -0.14960578 -0.13785519 -0.11315618 -0.14960578 -0.13785519
  -0.11315618 -0.14960578 -0.13785519]
 [-0.04836457  0.11699509 -0.10365508 -0.04836457  0.11699509 -0.10365508
  -0.04836457  0.11699509 -0.10365508]
 [-0.11315618 -0.14960578 -0.13785519 -0.11315618 -0.14960578 -0.13785519
  -0.11315618 -0.14960578 -0.13785519]
 [-0.04836457  0.11699509 -0.10365508 -0.04836457  0.11699509 -0.10365508
  -0.04836457  0.11699509 -0.10365508]
 [-0.11315618 -0.14960578 -0.13785519 -0.11315618 -0.14960578 -0.13785519
  -0.11315618 -0.14960578 -0.13785519]
 [-0.04836457  0.11699509 -0.10365508 -0.04836457  0.11699509 -0.10365508
  -0.04836457  0.11699509 -0.10365508]
 [-0.11315618 -0.14960578 -0.13785519 -0.11315618 -0.14960578 -0.13785519
  -0.11315618 -0.14960578 -0.13785519]
 [-0.04836457  0.

In [63]:
np.pi

3.141592653589793

In [6]:
arr = [1, 2, 3, 4, 5]
print arr[:-1]

[1, 2, 3, 4]


In [ ]:
n_features = 15


fc8_n_param   = [4096, n_features]

images = tf.placeholder(tf.float32, [None, 224, 224, 3])
labels = tf.placeholder(tf.float32, [None, n_features])

fc7 = net.layers['fc7']


W_fc8 = weight_variable(fc8_n_param)
b_fc8 = bias_variable([fc8_n_param[-1]])

fc8_pred = tf.matmul(fc7, W_fc8) + b_fc8

mse_loss = tf.reduce_mean(tf.square(labels - fc8_pred))
learning_rate = 1e-4
train_op = tf.train.AdamOptimizer(learning_rate).minimize(mse_loss)

saver = tf.train.Saver()

